### ISSUE TITLE
Missing package-lock.json file

### ISSUE THREAD

**Issue by LukasBicus** [toastmasters-kosice/toastmasters-kosice.github.io#1]
Hi Vlado, I see you have deleted package lock in 69262dd

There are some reasons to preserve it. 
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

Do you have a specific reason to remove it? If not, please add it back.

**Comment by vzahradnik** [comment]
I thought the file is only temporary, generated from package.json. Removing it from the repo didn't affect the building process as the file is present locally.

However, because I don't have any strong reason for removing it, I just put it back.

Thanks for notifying.

**Comment by LukasBicus** [comment]
package-lock is used because it grants, you have identical packages in environments - development, another development of your co-worker, and production (there no difference in minor/patches versions of libraries). Therefore there is good habit to keep it and deploy to production.
