### ISSUE TITLE
Webpage not indexed by search engines

### ISSUE THREAD

**Issue by vzahradnik** [toastmasters-kosice/toastmasters-kosice.github.io#4]
Our new webpage is still not indexed by Google and DuckDuckGo. I'll keep this issue open to track progress after a couple of days.

I also found out that our header contains title TM Košice. If search engines will pick up this name, we'll have to deal with it. People could have problems finding the web, as recent attempt by Vlado Kasarda showed.

**Comment by LukasBicus** [comment]
Check file `text.md`. There is `title: 'TM Košice'`

It's used in `Head` component. 
I used short name to display it in tab:
<img width="314" alt="Screen Shot 2019-06-11 at 20 44 03" src="https://user-images.githubusercontent.com/5645414/59297973-c846c480-8c89-11e9-82e3-9182422f2c1c.png">

We can change it to something else, what do you suggest?

**Comment by vzahradnik** [comment]
I suggest Toastmasters Košice. Such title was used also on our previous webpage. This will be more consistent, I suppose.

**Comment by vzahradnik** [comment]
Also, it would help if our webpage had a sitemap XML file. This will get better ranking and faster indexing by search engines. I will take a look into it.

And if you have no objections, I will rename TM Košice to Toastmasters Košice.

**Comment by vzahradnik** [comment]
Webpage title has been renamed to Toastmasters Košice. Automatic sitemap.xml generation was enabled and Google Analytics was set up. Closing this issue.
